# site settings
name: 2HAAS
title: 2HAAS | Draw Your Imagination
description: "ART is related with HEART.. It's the imagination which is framed in a canvas. Arts have no boundaries. And it's an opportunity to show your imagination to the world with 2HAAS.. Publish your Arts With 2HAAS. And that's why we say 'Draw Your Imagination'.."
language: "en-BD"
tags:
  - 2haas
  - 2HAAS
  - drawings
  - drawing
  - sketching
  - sketch
  - pencil sketch
  - oil pastel drawing
  - oil pastel drawings
  - graphics design
  - logo art

# advance settings
baseurl: ""
url: "https://2haas.com"
# url: "http://10.18.0.100:3000"
markdown: kramdown
markdown_ext: "markdown, mkdown, mkdn, mkd, md"
highlighter: rouge
sass:
    style: compressed

# google adsense setup
# ads_id: "ca-pub-7426762298315186"

# Social Media Settings

github_username: 2HAAS
facebook_username: 2haas
twitter_username: 2haas_tw
instagram_username: 2haas_insta
linkedin_username: 2haas
youtube_username: 2HAAS



# pagination plugin
# plugins:
  # - jekyll-paginate

# posts pagination
# paginate: 10
# paginate_path: "/page-:num"

# posts permalink
permalink: "/:title/"

# Author & Category setup
collections:
  authors:
    output: true
    sidebar_label: Authors
  categories:
    output: true
    sidebar_label: Categories


defaults:
  -
    scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  -
    scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

include:
  - .htaccess
